const { getRoleIdMap } = require('./sheets');

/**
 * Given a `lookupByEmail` result with status 'found', compute:
 *  - the list of role names to assign (resolved to Discord role IDs via the
 *    CONFIG sheet: column A = Role Name, column B = Discord Role UUID)
 *  - the suggested server nickname
 *  - a human-readable summary for the confirmation message
 *
 * Naming rule recap:
 *  - Format: `Nickname #Role1 #Role2...`
 *  - Core Team (col F checked) -> do NOT append "#Core Team" to the name,
 *    but DO assign the role.
 *  - Any role column whose cell is exactly "." -> do NOT append that role's
 *    tag to the name, but DO assign the role.
 *  - Any other role column with non-empty text -> assign the role AND
 *    append "#<ColumnName>" to the name.
 *
 * Role name matching against CONFIG is case-sensitive exact match, since
 * column H in ROLES is itself generated by a CONFIG-driven formula
 * (=TRANSPOSE(QUERY(CONFIG!A3:A, ...))), so the text should always match
 * verbatim unless someone hand-edits one side.
 */
async function computeAssignment(lookupResult) {
  const { fullname, nickname, email, coreTeam, roles } = lookupResult;
  const roleIdMap = await getRoleIdMap();

  const roleIdsToAssign = [];
  const roleNamesForDisplay = [];
  const nameTags = [];
  const unmappedRoles = [];

  if (coreTeam) {
    const roleId = roleIdMap.get('Core Team');
    if (roleId) {
      roleIdsToAssign.push(roleId);
    } else {
      unmappedRoles.push('Core Team');
    }
    roleNamesForDisplay.push('Core Team');
    // Core Team never appended to nickname, per spec.
  }

  for (const role of roles) {
    if (!role.hasValue) continue; // empty cell -> not assigned

    const roleId = roleIdMap.get(role.name);
    if (roleId) {
      roleIdsToAssign.push(roleId);
    } else {
      unmappedRoles.push(role.name);
    }
    roleNamesForDisplay.push(role.name);

    if (!role.isDotOnly) {
      nameTags.push(`#${role.rawValue}`);
    }
  }

  const suggestedNickname = nameTags.length > 0 ? `${nickname} ${nameTags.join(' ')}` : nickname;

  return {
    fullname,
    nickname,
    email,
    suggestedNickname,
    roleIdsToAssign,
    roleNamesForDisplay,
    unmappedRoles, // role names found in the sheet but missing/blank in CONFIG
  };
}

module.exports = { computeAssignment };
